In [5]:
#Importing Libraries, Setting Env
import json
from pprint import pprint
import pandas as pd
pd.set_option('display.max_columns', 35)

### Sample Data Structure

In [6]:
import json
from pprint import pprint

with open('refugees to DRC per DRC region.json') as f:
    data = json.load(f)

pprint(data)

{'chartType': 'areaspline',
 'color': '#3c8dbc',
 'data': [{'admin_level': 'Province',
           'centroid_lat': '3.5845154',
           'centroid_lon': '28.299435',
           'color': '#3c8dbc',
           'date': '2018-10-31',
           'demography_type': '1',
           'geomaster_id': 4826,
           'geomaster_name': 'Haut-Uele',
           'households': '0',
           'individuals': '49554',
           'individuals_type': '2',
           'lat_max': 5.1866504417685,
           'lat_min': 2.2763552727767,
           'lon_max': 30.8623046875,
           'lon_min': 26.55224609375,
           'month': '10',
           'numChildren': '0',
           'population_group_id': '4949, 4768, 5075',
           'population_groups': [{'id': '4768',
                                  'name': 'Registered refugees from South '
                                          'Sudan (rural/dispersed areas, '
                                          'UNHCR)',
                                  'pop_accommodation_code': 'R',
                                  'pop_accommodation_name': 'Rural/Dispersed '
                                                            'Areas',
                                  'pop_data_type_code': 'REG',
                                  'pop_data_type_name': 'Registered',
                                  'pop_frequency_code': 'D',
                                  'pop_frequency_cumulative': 'cumulative',
                                  'pop_frequency_cumulative_code': 'C',
                                  'pop_frequency_name': 'Daily',
                                  'pop_origin_code': 'SSD',
                                  'pop_origin_name': 'South Sudan',
                                  'pop_type_code': 'REF',
                                  'pop_type_name': 'Refugees'},
                                 {'id': '4949',
                                  'name': 'Registered refugees from South '
                                          'Sudan  (refugee camps/centers, '
                                          'UNHCR)',
                                  'pop_accommodation_code': 'C',
                                  'pop_accommodation_name': 'Refugee '
                                                            'Camps/Centers',
                                  'pop_data_type_code': 'REG',
                                  'pop_data_type_name': 'Registered',
                                  'pop_frequency_code': 'D',
                                  'pop_frequency_cumulative': 'cumulative',
                                  'pop_frequency_cumulative_code': 'C',
                                  'pop_frequency_name': 'Daily',
                                  'pop_origin_code': 'SSD',
                                  'pop_origin_name': 'South Sudan',
                                  'pop_type_code': 'REF',
                                  'pop_type_name': 'Refugees'},
                                 {'id': '5075',
                                  'name': 'Registered refugees from South '
                                          'Sudan (rural/dispersed areas)',
                                  'pop_accommodation_code': 'R',
                                  'pop_accommodation_name': 'Rural/Dispersed '
                                                            'Areas',
                                  'pop_data_type_code': 'REG',
                                  'pop_data_type_name': 'Registered',
                                  'pop_frequency_code': 'D',
                                  'pop_frequency_cumulative': 'cumulative',
                                  'pop_frequency_cumulative_code': 'C',
                                  'pop_frequency_name': 'Daily',
                                  'pop_origin_code': 'SSD',
                                  'pop_origin_name': 'South Sudan',
                                  'pop_type_code': 'REF',
                                  'pop_type_name': 'Refugees'}],
           'population_groups_concat': 'Registered refugees from South Sudan  '
                                       '(refugee camps/centers, UNHCR), '
                                       'Registered refugees from South Sudan '
                                       '(rural/dispersed areas, UNHCR), '
                                       'Registered refugees from South Sudan '
                                       '(rural/dispersed areas)',
           'published': False,
           'source': 'UNHCR',
           'year': '2018'},
          {'admin_level': 'Province',
           'centroid_lat': '1.85',
           'centroid_lon': '29.966667',
           'color': '#3c8dbc',
           'date': '2018-10-31',
           'demography_type': '1',
           'geomaster_id': 4827,
           'geomaster_name': 'Ituri',
           'households': '0',
           'individuals': '45528',
           'individuals_type': '1',
           'lat_max': 4.0477992916745,
           'lat_min': 0.62899251377087,
           'lon_max': 31.45556640625,
           'lon_min': 28.7275390625,
           'month': '10',
           'numChildren': '0',
           'population_group_id': '4768, 4949, 5075',
           'population_groups': [{'id': '4768',
                                  'name': 'Registered refugees from South '
                                          'Sudan (rural/dispersed areas, '
                                          'UNHCR)',
                                  'pop_accommodation_code': 'R',
                                  'pop_accommodation_name': 'Rural/Dispersed '
                                                            'Areas',
                                  'pop_data_type_code': 'REG',
                                  'pop_data_type_name': 'Registered',
                                  'pop_frequency_code': 'D',
                                  'pop_frequency_cumulative': 'cumulative',
                                  'pop_frequency_cumulative_code': 'C',
                                  'pop_frequency_name': 'Daily',
                                  'pop_origin_code': 'SSD',
                                  'pop_origin_name': 'South Sudan',
                                  'pop_type_code': 'REF',
                                  'pop_type_name': 'Refugees'},
                                 {'id': '4949',
                                  'name': 'Registered refugees from South '
                                          'Sudan  (refugee camps/centers, '
                                          'UNHCR)',
                                  'pop_accommodation_code': 'C',
                                  'pop_accommodation_name': 'Refugee '
                                                            'Camps/Centers',
                                  'pop_data_type_code': 'REG',
                                  'pop_data_type_name': 'Registered',
                                  'pop_frequency_code': 'D',
                                  'pop_frequency_cumulative': 'cumulative',
                                  'pop_frequency_cumulative_code': 'C',
                                  'pop_frequency_name': 'Daily',
                                  'pop_origin_code': 'SSD',
                                  'pop_origin_name': 'South Sudan',
                                  'pop_type_code': 'REF',
                                  'pop_type_name': 'Refugees'},
                                 {'id': '5075',
                                  'name': 'Registered refugees from South '
                                          'Sudan (rural/dispersed areas)',
                                  'pop_accommodation_code': 'R',
                                  'pop_accommodation_name': 'Rural/Dispersed '
                                                            'Areas',
                                  'pop_data_type_code': 'REG',
                                  'pop_data_type_name': 'Registered',
                                  'pop_frequency_code': 'D',
                                  'pop_frequency_cumulative': 'cumulative',
                                  'pop_frequency_cumulative_code': 'C',
                                  'pop_frequency_name': 'Daily',
                                  'pop_origin_code': 'SSD',
                                  'pop_origin_name': 'South Sudan',
                                  'pop_type_code': 'REF',
                                  'pop_type_name': 'Refugees'}],
           'population_groups_concat': 'Registered refugees from South Sudan '
                                       '(rural/dispersed areas, UNHCR), '
                                       'Registered refugees from South Sudan  '
                                       '(refugee camps/centers, UNHCR), '
                                       'Registered refugees from South Sudan '
                                       '(rural/dispersed areas)',
           'published': False,
           'source': 'UNHCR',
           'year': '2018'},
          {'admin_level': 'Province',
           'centroid_lat': '-5.44102',
           'centroid_lon': '15.9961',
           'color': '#3c8dbc',
           'date': '2018-05-31',
           'demography_type': '1',
           'geomaster_id': 4837,
           'geomaster_name': 'Kinshasa',
           'households': '0',
           'individuals': '50',
           'individuals_type': '1',
           'lat_max': 1.55898,
           'lat_min': -12.44102,
           'lon_max': 22.9961,
           'lon_min': 8.9961,
           'month': '5',
           'numChildren': '1',
           'population_group_id': '4768',
           'population_groups': [{'id': '4768',
                                  'name': 'Registered refugees from South '
                                          'Sudan (rural/dispersed areas, '
                                          'UNHCR)',
                                  'pop_accommodation_code': 'R',
                                  'pop_accommodation_name': 'Rural/Dispersed '
                                                            'Areas',
                                  'pop_data_type_code': 'REG',
                                  'pop_data_type_name': 'Registered',
                                  'pop_frequency_code': 'D',
                                  'pop_frequency_cumulative': 'cumulative',
                                  'pop_frequency_cumulative_code': 'C',
                                  'pop_frequency_name': 'Daily',
                                  'pop_origin_code': 'SSD',
                                  'pop_origin_name': 'South Sudan',
                                  'pop_type_code': 'REF',
                                  'pop_type_name': 'Refugees'}],
           'population_groups_concat': 'Registered refugees from South Sudan '
                                       '(rural/dispersed areas, UNHCR)',
           'published': False,
           'source': 'UNHCR',
           'year': '2018'},
          {'admin_level': 'Province',
           'centroid_lat': '3.9901009',
           'centroid_lon': '24.904220799999962',
           'color': '#3c8dbc',
           'date': '2017-12-31',
           'demography_type': '1',
           'geomaster_id': 4810,
           'geomaster_name': 'Bas-Uele',
           'households': '0',
           'individuals': '49',
           'individuals_type': '1',
           'lat_max': 6.126862843542,
           'lat_min': 2.6495447022079,
           'lon_max': 26.423828125,
           'lon_min': 22.794921875,
           'month': '12',
           'numChildren': '0',
           'population_group_id': '4768',
           'population_groups': [{'id': '4768',
                                  'name': 'Registered refugees from South '
                                          'Sudan (rural/dispersed areas, '
                                          'UNHCR)',
                                  'pop_accommodation_code': 'R',
                                  'pop_accommodation_name': 'Rural/Dispersed '
                                                            'Areas',
                                  'pop_data_type_code': 'REG',
                                  'pop_data_type_name': 'Registered',
                                  'pop_frequency_code': 'D',
                                  'pop_frequency_cumulative': 'cumulative',
                                  'pop_frequency_cumulative_code': 'C',
                                  'pop_frequency_name': 'Daily',
                                  'pop_origin_code': 'SSD',
                                  'pop_origin_name': 'South Sudan',
                                  'pop_type_code': 'REF',
                                  'pop_type_name': 'Refugees'}],
           'population_groups_concat': 'Registered refugees from South Sudan '
                                       '(rural/dispersed areas, UNHCR)',
           'published': False,
           'source': 'UNHCR',
           'year': '2017'}],
 'frequency': 'day',
 'limit': '',
 'situation_view_description': 'The situation in South Sudan and neighbouring '
                               'countries has quickly escalated into a '
                               'full-blown humanitarian emergency. \r\n'
                               'The majority of the refugees are women and '
                               'children, many of whom flee across the border '
                               'alone. Often, they arrive weak and '
                               'malnourished. When the rainy season comes, '
                               'their needs are compounded by flooding, food '
                               'shortages and disease.\r\n'
                               'Inside South Sudan, nearly two million people '
                               'are displaced internally, while outside the '
                               'country there are now over two million South '
                               'Sudanese refugees, mainly in Ethiopia, Sudan, '
                               'and Uganda. Many fear imminent attack or '
                               'struggle with food insecurity. Uganda '
                               'currently hosts the most South Sudanese '
                               'refugees, having taken in more than one '
                               'million.',
 'situation_view_id': '5',
 'situation_view_name': 'South Sudan',
 'subtitle_language_ar': '',
 'subtitle_language_en': '',
 'subtitle_language_es': '',
 'subtitle_language_fr': '',
 'title_language_ar': '',
 'title_language_en': 'Breakdown by Region',
 'title_language_es': '',
 'title_language_fr': ''}

### Process to Extract Data

In [17]:
files = ['refugees to Kenya per sex','refugees to Kenya per location', 'refugees to DRC per DRC region', 'refugees to Ethiopia per Ethiopian district','refugees to Sudan per Sudanese state','refugees to Uganda per Ugandan district']

for file in files:
    with open(file + '.json') as f:
        data = json.load(f)
        
    new_df = pd.DataFrame(data['data'])
    new_df.to_csv(file + "_cleaned.csv", sep=',')

#### Extracted Data

In [18]:
from IPython.display import display
for file in files:
    df = pd.read_csv(file + '_cleaned.csv')
    print("#File: " + file)
    display(df.head())

#File: refugees to Kenya per sex

,Unnamed: 0,admin_level,centroid_lat,centroid_lon,children_total,date,demography_type,female_04,female_1217,female_1859,female_511,female_60,female_hhs,female_total,geomaster_id,geomaster_name,households,...,lat_min,lon_max,lon_min,male_04,male_1217,male_1859,male_511,male_60,male_hhs,male_total,month,population_group_id,population_groups,population_groups_concat,source,uac_total,year
0,0,Country,0.537253,37.8802,72029,2018-10-31,1,7934,10126,20816,14074,985,15789,53935,178,Kenya,25412,...,-4.800945,42.419263,33.560864,8301,15261,20195,16333,366,9623,60456,10,4949,"[{'id': '4949', 'name': 'Registered refugees f...",Registered refugees from South Sudan (refugee...,UNHCR,62,2018

#File: refugees to Kenya per location

,Unnamed: 0,admin_level,centroid_lat,centroid_lon,color,date,demography_type,geomaster_id,geomaster_name,households,individuals,individuals_type,lat_max,lat_min,lon_max,lon_min,month,numChildren,population_group_id,population_groups,population_groups_concat,published,source,year
0,0,District,3.039887,35.620705,#3c8dbc,2018-10-31,1,6163,Turkana,22632,107672,2,5.425336,0.738858,38.577736,33.674416,10,0,4949,"[{'id': '4949', 'name': 'Registered refugees f...",Registered refugees from South Sudan (refugee...,False,UNHCR,2018
1,1,Province,-1.291470,36.823300,#3c8dbc,2018-08-31,1,1868,Nairobi,2500,5763,2,-0.850422,-1.636532,37.383938,36.180264,8,0,4949,"[{'id': '4949', 'name': 'Registered refugees f...",Registered refugees from South Sudan (refugee...,False,UNHCR,2018
2,2,Province,-0.453229,39.646099,#3c8dbc,2018-08-31,1,6162,Garissa,280,956,2,2.912347,-2.024699,42.822857,37.963482,8,0,4949,"[{'id': '4949', 'name': 'Registered refugees f...",Registered refugees from South Sudan (refugee...,False,UNHCR,2018

#File: refugees to DRC per DRC region

,Unnamed: 0,admin_level,centroid_lat,centroid_lon,color,date,demography_type,geomaster_id,geomaster_name,households,individuals,individuals_type,lat_max,lat_min,lon_max,lon_min,month,numChildren,population_group_id,population_groups,population_groups_concat,published,source,year
0,0,Province,3.584515,28.299435,#3c8dbc,2018-10-31,1,4826,Haut-Uele,0,49554,2,5.186650,2.276355,30.862305,26.552246,10,0,"4949, 4768, 5075","[{'id': '4768', 'name': 'Registered refugees f...",Registered refugees from South Sudan (refugee...,False,UNHCR,2018
1,1,Province,1.850000,29.966667,#3c8dbc,2018-10-31,1,4827,Ituri,0,45528,1,4.047799,0.628993,31.455566,28.727539,10,0,"4768, 4949, 5075","[{'id': '4768', 'name': 'Registered refugees f...",Registered refugees from South Sudan (rural/di...,False,UNHCR,2018
2,2,Province,-5.441020,15.996100,#3c8dbc,2018-05-31,1,4837,Kinshasa,0,50,1,1.558980,-12.441020,22.996100,8.996100,5,1,4768,"[{'id': '4768', 'name': 'Registered refugees f...",Registered refugees from South Sudan (rural/di...,False,UNHCR,2018
3,3,Province,3.990101,24.904221,#3c8dbc,2017-12-31,1,4810,Bas-Uele,0,49,1,6.126863,2.649545,26.423828,22.794922,12,0,4768,"[{'id': '4768', 'name': 'Registered refugees f...",Registered refugees from South Sudan (rural/di...,False,UNHCR,2017

#File: refugees to Ethiopia per Ethiopian district

,Unnamed: 0,admin_level,centroid_lat,centroid_lon,color,date,demography_type,geomaster_id,geomaster_name,households,individuals,individuals_type,lat_max,lat_min,lon_max,lon_min,month,numChildren,population_group_id,population_groups,population_groups_concat,published,source,year
0,0,Region,7.833330,34.500000,#3c8dbc,2018-08-31,1,1849,Gambela,0,401507,2,14.833330,0.833330,41.500000,27.500000,8,17,4949,"[{'id': '4949', 'name': 'Registered refugees f...",Registered refugees from South Sudan (refugee...,False,UNHCR,2018
1,1,Region,10.780289,35.565786,#3c8dbc,2018-08-31,1,6035,Benishangul-Gumuz,0,17400,2,17.780289,3.780289,42.565786,28.565786,8,0,4949,"[{'id': '4949', 'name': 'Registered refugees f...",Registered refugees from South Sudan (refugee...,False,UNHCR,2018
2,2,Region,6.515691,36.954107,#3c8dbc,2018-05-31,1,6034,SNNPR,0,2787,2,8.004691,5.026691,38.889807,35.018407,5,0,4949,"[{'id': '4949', 'name': 'Registered refugees f...",Registered refugees from South Sudan (refugee...,False,UNHCR,2018
3,3,Region,9.000380,38.750700,#3c8dbc,2018-08-31,1,1841,Addis Ababa,0,546,2,16.000380,2.000380,45.750700,31.750700,8,1,4949,"[{'id': '4949', 'name': 'Registered refugees f...",Registered refugees from South Sudan (refugee...,False,UNHCR,2018

#File: refugees to Sudan per Sudanese state

,Unnamed: 0,admin_level,centroid_lat,centroid_lon,color,date,demography_type,geomaster_id,geomaster_name,households,individuals,individuals_type,lat_max,lat_min,lon_max,lon_min,month,numChildren,population_group_id,population_groups,population_groups_concat,published,source,year
0,0,Town,15.000000,32.000000,#3c8dbc,2017-11-15,1,1907,Khartoum,0,285705,1,22.000000,8.000000,39.000000,25.000000,11,0,5072,"[{'id': '5072', 'name': 'Registered refugees f...",Registered refugees from South Sudan (refugee...,False,"UNHCR, IOM, SRCS, COR, HAC",2017
1,1,Region,13.340000,32.420000,#3c8dbc,2018-10-31,1,1913,White Nile,0,176224,1,20.340000,8.518684,39.420000,25.420000,10,0,5072,"[{'id': '5072', 'name': 'Registered refugees f...",Registered refugees from South Sudan (refugee...,False,"UNHCR, IOM, SRCS, COR, HAC",2018
2,2,Region,11.077000,26.844000,#3c8dbc,2018-10-31,1,1906,East Darfur,0,99023,1,12.101714,10.052286,28.176129,25.511871,10,0,5072,"[{'id': '5072', 'name': 'Registered refugees f...",Registered refugees from South Sudan (refugee...,False,"UNHCR, IOM, SRCS, COR, HAC",2018
3,3,Region,11.719200,28.329399,#3c8dbc,2018-10-31,1,1912,West Kordofan,0,58743,1,13.359057,10.079343,30.461213,26.197585,10,0,5072,"[{'id': '5072', 'name': 'Registered refugees f...",Registered refugees from South Sudan (refugee...,False,"UNHCR, IOM, SRCS, COR, HAC",2018
4,4,Region,10.884764,30.915924,#3c8dbc,2018-10-31,1,1911,South Kordofan,0,38225,1,12.486200,9.542200,31.643001,27.815801,10,0,5072,"[{'id': '5072', 'name': 'Registered refugees f...",Registered refugees from South Sudan (refugee...,False,"UNHCR, IOM, SRCS, COR, HAC",2018

#File: refugees to Uganda per Ugandan district

,Unnamed: 0,admin_level,centroid_lat,centroid_lon,color,date,demography_type,geomaster_id,geomaster_name,households,individuals,individuals_type,lat_max,lat_min,lon_max,lon_min,month,numChildren,population_group_id,population_groups,population_groups_concat,published,source,year
0,0,District,3.538595,31.300605,#3c8dbc,2018-10-31,1,6032,Yumbe,0,222958,1,4.178452,2.898738,32.132419,30.468790,10,0,5071,"[{'id': '5071', 'name': 'Registered refugees f...",Registered refugees from South Sudan (refugee ...,False,Office of the Prime Minister,2018
1,1,District,3.458590,31.778000,#3c8dbc,2018-10-31,1,1926,Adjumani,0,201885,1,4.090617,2.519511,32.799057,30.756943,10,14,5071,"[{'id': '5071', 'name': 'Registered refugees f...",Registered refugees from South Sudan (refugee ...,False,Office of the Prime Minister,2018
2,2,Region,3.030810,31.245100,#3c8dbc,2018-10-31,1,1941,Arua,0,149373,1,3.545810,2.515810,31.914600,30.575600,10,3,5071,"[{'id': '5071', 'name': 'Registered refugees f...",Registered refugees from South Sudan (refugee ...,False,Office of the Prime Minister,2018
3,3,District,3.620832,31.727698,#3c8dbc,2018-10-31,1,6031,Moyo,0,118377,1,4.098403,3.143260,32.348541,31.106855,10,0,5071,"[{'id': '5071', 'name': 'Registered refugees f...",Registered refugees from South Sudan (refugee ...,False,Office of the Prime Minister,2018
4,4,District,1.940342,32.180172,#3c8dbc,2018-10-31,1,1948,Kiryandongo,0,53221,1,2.902913,0.977770,33.431515,30.928829,10,1,5071,"[{'id': '5071', 'name': 'Registered refugees f...",Registered refugees from South Sudan (refugee ...,False,Office of the Prime Minister,2018